pipeline {
    agent  { label 'agent-1' }

    stages {
        stage('Build') {
            steps {
                script{
                   sh  """
                        echo 'Building..'
                    """
                }
                
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
        }
        changed { 
            echo ' changed Hello again!'
        }
        failure { 
            echo 'I will always say Hello on failure!'
        }
    }
}